services:
  jenkins:
    build:
      context: .
      dockerfile: jenkins-local.Dockerfile
    container_name: jenkins-minitaller
    user: root
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/workspace/Minitaller-Jenkins

  develop:
    build:
      context: .
      target: develop
    environment:
      DISPLAY: ${DISPLAY}
    volumes:
      - .:/app
      - /tmp/.X11-unix:/tmp/.X11-unix
    command: python buscaminas.py

  unit-test:
    build:
      context: .
      target: unit-test
    command: python -m unittest discover -s tests

volumes:
  jenkins_home:
